name: Mirror Git repos

on:
  schedule:
    - cron: '25 5 * * *'
  workflow_dispatch:

jobs:
  pagure-io-go:
    name: Mirror `https://pagure.io/go`
    runs-on: ubuntu-latest
    steps:
      - name: Restore repo from cache
        id: cache-repo
        uses: actions/cache@v2
        with:
          path: ${{ github.job }}
          key: ${{ github.job }}-${{ github.run_number }}
          restore-keys: |
            ${{ github.job }}-

      - name: Clone repo (if not restored)
        run: |
          if [[ ! -e ${{ github.job }} ]]; then
            git clone --mirror https://pagure.io/go.git ${{ github.job }}
          fi

      - name: Update repo
        working-directory: ${{ github.job }}
        run: git remote update --prune origin

      - name: Configure SSH deploy key
        uses: webfactory/ssh-agent@5f066a372ec13036ab7cb9a8adf18c936f8d2043 # v0.5.3
        with:
          # Deploy key comment must include the GitHub repo:
          # https://github.com/webfactory/ssh-agent#support-for-github-deploy-keys
          ssh-private-key: ${{ secrets.DEPLOY_KEY_PAGURE_IO_GO }}

      - name: Push repo to mirror
        working-directory: ${{ github.job }}
        run: |
          # Ignore errors like:
          # ! [remote rejected] refs/pull/1/head -> refs/pull/1/head (deny updating a hidden ref)
          # ! [remote rejected] refs/pull/2/head -> refs/pull/2/head (deny updating a hidden ref)
          # ! [remote rejected] refs/pull/3/head -> refs/pull/3/head (deny updating a hidden ref)
          # error: failed to push some refs to 'github.com:jjlin/golang-fips.git'
          git push --mirror git@github.com:jjlin/golang-fips.git || true

      - name: Run housekeeping on cached repo
        working-directory: ${{ github.job }}
        run: git gc --auto
